### ISSUE TITLE
Ошибка в логике игры

### ISSUE THREAD

**Issue by protsenkovi** [PavelPimKot/TPLAB2#1]
Похоже сообщения больше/меньше перепутаны местами.

```
Загадайте число:
11
```

```
Игра началась
Предположите цифру :
12
Введенное число меньше чем загаданное
Предположите цифру :
9
Введенное число больше чем загаданное
```

**Comment by PavelPimKot** [comment]
Поправил в
 https://github.com/PavelPimKot/TPLAB2/commit/23e5bbc35bf369cd025427d27d7018e048673d90

**Comment by PavelPimKot** [comment]
Так же добавил в ветке LAB3 реализацию 3ей лабораторной работы, сделал в отдельной ветке, т.к. возможно мог не так понять задание.
